### ISSUE TITLE
Add PKCS#7/Cryptographic Message Syntax Support

### ISSUE THREAD

**Issue by TheGeekPharaoh** [vapor/open-crypto#44]
I’d love to see support for PKCS#7/Cryptographic Message Syntax (CMS) added to Vapor Crypto.  It would allow me to, for example, sign or encrypt iOS configuration profiles (https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/iPhoneOTAConfiguration/profile-service/profile-service.html#//apple_ref/doc/uid/TP40009505-CH2-SW37).  At the very least I can replace a HUGE amount of my Java EE code base with server-side Swift.

**Comment by rafiki270** [comment]
+ 1 on this one! Boost needs an MDM :))))

**Comment by sdnakhla** [comment]
That's EXACTLY what I'm working on right now, @rafiki270!  If it weren't for the need for CMS signatures, I'd be able to port 100% of my code over to Swift.  It's the last missing piece.  I've begun working on it myself with OpenSSL, but it's slow going.

**Comment by bre7** [comment]
You could try using [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) until it's added

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
