### ISSUE TITLE
add ECDSA support

### ISSUE THREAD

**Issue by tanner0101** [vapor/open-crypto#73]

**Comment by phlebotinum** [comment]
This would be greatly appreciated!

**Comment by jonblatho** [comment]
Any update on plans for this? I'd be happy to help where I can as a good number of projects (including some of mine) seem to await some Linux-supporting implementation of ECDSA mostly for interacting with Apple's services.

**Comment by tanner0101** [comment]
There's a working implementation here that we could use for reference: https://github.com/vapor-community/apns/blob/master/Sources/APNS/Extensions/JWT%2BES256.swift

**Comment by tanner0101** [comment]
Another implementation here: https://github.com/kylebrowning/swift-nio-http2-apns/blob/master/Sources/NIOAPNS/DataSigner.swift

**Comment by dougreid72** [comment]
The new JWTKit 4.0 alpha now includes this functionality.   This issue could be closed or attached to JWTKit.  Unless you intend to add the functionality for Vapor 3 also.

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
