### ISSUE TITLE
generate RSA keys

### ISSUE THREAD

**Issue by v57** [vapor/open-crypto#83]
I want to generate `rsa-4096` key and encrypt data using tag, `oaep` padding and `sha1` digest. How can i do this?

**Comment by tanner0101** [comment]
This package doesn't have any methods for generating RSA keys. It only supports reading existing RSA keys for used with signing and verification: https://api.vapor.codes/crypto/latest/Crypto/Structs/RSAKey.html

I'll change this issue to be a feature request for RSA key generation.

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
