### ISSUE TITLE
Support for DER encoded x509 certificate.

### ISSUE THREAD

**Issue by emarashliev** [vapor/open-crypto#85]
Hey Guys I need support for DER encoded x509 certificate. Here is the implementation I made #86  .

**Comment by emarashliev** [comment]
Also it would be great the design of RSAKey and  CRSAKey to be more opened  so it's easy extend them in the clients code base . I have some ideas about this as well.

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
