### ISSUE TITLE
Using with iOS

### ISSUE THREAD

**Issue by mattmaddux** [vapor/open-crypto#90]
I'm guessing there is no way to include this in an iOS project? I'm using Vapor on my backend and it would be really convenient to use the same library for encrypting at the server and decrypting at the client side.

**Comment by d4r1091** [comment]
@mattmaddux if you are using **SwiftPackageManager** it should be easy to include.

add this:
        ```.package(url: "https://github.com/vapor/open-crypto.git", .branch("master")), ```
in your dependencies' array

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
