### ISSUE TITLE
Crash when decrypting base64 encoded secret

### ISSUE THREAD

**Issue by rafiki270** [vapor/open-crypto#97]
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: CryptoKit.CryptoError(identifier: "EVP_CipherFinal_ex", reason: "Failed finishing cipher.: error:00000000:lib(0):func(0):reason(0).")
This is my library to encrypt/decrypt passwords for remote nodes on my CI:
https://github.com/Einstore/Speedster/blob/master/Sources/SpeedsterApi/Libs/Secrets.swift
the tests for it here:
https://github.com/Einstore/Speedster/blob/master/Tests/SpeedsterApiTests/SecretsTests.swift

It only crashes if the secret has been decoded from base64 string ...

**Comment by 0xTim** [comment]
Closing as Swift Crypto is now used instead of this library
